### ISSUE TITLE
Pretrained models

### ISSUE THREAD

**Issue by robo-warrior** [lemoner20/ICIP2018#1]
Hi! In which directory do one put the pretrained models and is there any path change that needs to be corrected in any files for using pretrained model?

**Comment by lemoner20** [comment]
Hi，you can put the pretrained model in ./checkpoint/*.npz folder and put the Faceparsing.h5 file in the root folder. If you just use the model we provide, then you don't need to change the path. Otherwise, you need to change the path in the code if you try training. Good luck！

**Comment by robo-warrior** [comment]
Thanks :)
